import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# פונקציה לחישוב תשלום חודשי קבוע
def calculate_monthly_payment(principal, rate, years):
    monthly_rate = rate / 100 / 12
    months = years * 12
    if monthly_rate == 0:
        return principal / months
    return principal * (monthly_rate * (1 + monthly_rate) ** months) / ((1 + monthly_rate) ** months - 1)

# פונקציה לחישוב תשלומים עם הצמדה למדד ושינויי ריבית
def calculate_adjusted_monthly_payment(principal, rate, years, variable_rate_change, early_payment, inflation):
    adjusted_payments = []
    balance = principal
    for month in range(1, years * 12 + 1):
        if variable_rate_change and month in variable_rate_change:
            rate = variable_rate_change[month]
        monthly_payment = calculate_monthly_payment(balance, rate, years - (month // 12))
        if early_payment > 0 and month % 12 == 0:
            balance -= early_payment
        balance *= (1 + inflation / 100 / 12)  # הצמדה למדד
        adjusted_payments.append(monthly_payment)
    return np.mean(adjusted_payments)

# פונקציה ראשית להצגת ממשק האפליקציה
def main():
    st.title("תמהיל משכנתא - אפליקציה אינטרנטית")

    st.sidebar.header("הזן נתונים")
    st.sidebar.write("**טווח מומלץ למשכנתא: 200,000 - 2,500,000 ₪**")
    total_loan = st.sidebar.number_input("סכום המשכנתא (₪)", min_value=50000, max_value=5000000, step=50000, value=1000000)
    num_components = st.sidebar.number_input("מספר מסלולים", min_value=1, max_value=5, step=1, value=3)

    st.write("### פירוט מסלולים")
    data = []

    for i in range(num_components):
        st.subheader(f"מס
